import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import {UserInfoProvider} from "@/context/user";
import 'bootstrap-icons/font/bootstrap-icons.css';
export const metadata: Metadata = {
  title: "mailbox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserInfoProvider>
      <body>
        {children}
      </body>
      </UserInfoProvider>
    </html>
  );
}
